version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Running tests `date`
      - mvn clean install

  post_build:
    commands:
      - echo Building project started on `date`
      - mvn install package
artifacts:
  files:
    - '**/*.jar'
cache:
  paths:
    - '/root/.m2/**/*'


