version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
artifacts:
  files:
    #- service/target/*.jar
    - service/target/service-0.0.1-SNAPSHOT.jar

  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'

