CREATE TABLE room (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name varchar(20) NOT NULL,
	seat INT NOT NULL,
	active TINYINT NOT NULL,
	CONSTRAINT room_pk PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;