# ===========================
# = Spring
# ===========================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://realmeet-db.cjkk0202e4rl.us-east-1.rds.amazonaws.com:3306/realmeet?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: admin